import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const routes=[
  ['Hà Nội → Hà Giang','~320 km','4 ngày','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85'],
  ['Hà Nội → Cao Bằng','~280 km','3 ngày','https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=900&q=85'],
  ['Hà Nội → Mộc Châu','~200 km','2 ngày','https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=85'],
  ['Hà Nội → Cát Bà','~160 km','2 ngày','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85']
];
const tools=[['⛽','Cây xăng','gas station'],['🔧','Sửa xe','motorcycle repair'],['🍜','Ăn uống','restaurant'],['🛏️','Chỗ nghỉ','hotel'],['🏥','Y tế','hospital'],['📍','Điểm hot','tourist attraction']];
const searchMaps=q=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,'_blank');
const directions=(a,b)=>window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(a)}&destination=${encodeURIComponent(b)}&travelmode=driving`,'_blank');

function Nav({page,setPage}){return <header className="nav"><button className="logo" onClick={()=>setPage('home')}><span>▲</span>RideMate</button><nav>{[['home','Khám phá'],['create','Lên kế hoạch'],['tools','Công cụ'],['journal','Nhật ký hành trình'],['ai','AI Assistant']].map(([k,v])=><button className={page===k?'active':''} onClick={()=>setPage(k)} key={k}>{v}</button>)}</nav><div className="user">🔔 <b>N</b> Xin chào, Ngọc</div></header>}

function Home({trip,setTrip,setPage}){return <main className="dash"><div className="maincol">
  <section className="hero"><div><small>RIDE MORE · EXPLORE FURTHER</small><h1>Những cung đường<br/>đẹp hơn khi đi cùng<br/>RideMate</h1><p>Lên kế hoạch dễ dàng · Hành trình an toàn hơn · Trải nghiệm nhiều hơn.</p></div>
    <div className="tripbar"><label>Điểm xuất phát<input value={trip.origin} onChange={e=>setTrip({...trip,origin:e.target.value})}/></label><label>Điểm đến<input value={trip.destination} onChange={e=>setTrip({...trip,destination:e.target.value})}/></label><label>Ngày đi<input type="date" value={trip.date} onChange={e=>setTrip({...trip,date:e.target.value})}/></label><label>Số ngày<input type="number" value={trip.days} onChange={e=>setTrip({...trip,days:e.target.value})}/></label><button className="orange" onClick={()=>setPage('trip')}>Tạo chuyến đi →</button></div>
  </section>
  <section className="box"><div className="title"><h2>Công cụ hỗ trợ nhanh</h2><button onClick={()=>setPage('tools')}>Xem tất cả →</button></div><div className="quick"><button onClick={()=>setPage('checklist')}><span>✅</span>Checklist</button>{tools.map(t=><button key={t[1]} onClick={()=>searchMaps(t[2])}><span>{t[0]}</span>{t[1]}</button>)}<button onClick={()=>setPage('ai')}><span>➤</span>AI Assistant</button></div></section>
  <section><div className="title"><h2>Gợi ý cung đường nổi bật</h2><div className="tabs">Miền Bắc · Miền Trung · Miền Nam</div></div><div className="routes">{routes.map(r=><article key={r[0]}><img src={r[3]}/><div><h3>{r[0]}</h3><small>◈ {r[1]} &nbsp; ◷ {r[2]}</small><p>Cung đường giàu trải nghiệm, phù hợp cho chuyến đi tự túc bằng xe máy.</p></div></article>)}</div></section>
</div><aside className="side"><section className="box"><div className="title"><h2>Chuyến đi sắp tới</h2><button onClick={()=>setPage('trip')}>Xem chi tiết →</button></div><div className="upcoming"><img src={routes[0][3]}/><div><h3>{trip.origin} → {trip.destination}</h3><small>15/09 – 18/09/2026 · {trip.days} ngày</small><p>✓ Lịch trình (3/4)<br/>✓ Checklist (12/20)<br/>✓ Địa điểm đã lưu (5)</p></div><b className="ring">60%</b></div><button className="green full" onClick={()=>setPage('trip')}>Xem chi tiết chuyến đi →</button></section>
<section className="box"><div className="title"><h2>Bản đồ gợi ý</h2><button onClick={()=>directions(trip.origin,trip.destination)}>Mở Google Maps ↗</button></div><iframe title="map" className="map" src={`https://www.google.com/maps?q=${encodeURIComponent(trip.destination)}&output=embed`}></iframe></section>
<section className="box"><div className="title"><h2>Nhật ký gần đây</h2><button onClick={()=>setPage('journal')}>Xem tất cả →</button></div>{routes.slice(1,4).map((r,i)=><div className="jmini" key={r[0]}><img src={r[3]}/><div><b>{r[0].replace('Hà Nội → ','')}</b><small>0{i+5}/08/2026</small><p>Một chuyến đi nhiều kỷ niệm...</p></div></div>)}</section></aside></main>}

function Create({trip,setTrip,setPage}){let interests=['Thiên nhiên','Văn hóa','Ẩm thực','Khám phá','Nghỉ dưỡng','Chụp ảnh'];return <main className="page"><h1>Tạo chuyến đi</h1><p>Chỉ vài bước để bắt đầu hành trình của bạn.</p><div className="create"><section className="card"><h3>Thông tin cơ bản</h3>{[['Điểm xuất phát','origin'],['Điểm đến','destination']].map(x=><label key={x[1]}>{x[0]}<input value={trip[x[1]]} onChange={e=>setTrip({...trip,[x[1]]:e.target.value})}/></label>)}<label>Ngày đi<input type="date" value={trip.date} onChange={e=>setTrip({...trip,date:e.target.value})}/></label><label>Số ngày<input type="number" value={trip.days} onChange={e=>setTrip({...trip,days:e.target.value})}/></label></section><section className="card"><h3>Sở thích chuyến đi</h3><div className="interest">{interests.map(x=><button key={x}>{x}</button>)}</div><label>Ghi chú<textarea placeholder="Ví dụ: ưu tiên cung đẹp, tránh đi đêm..."/></label><button className="green full" onClick={()=>setPage('trip')}>Tiếp tục →</button></section><aside className="quote"><img src="https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85"/><h2>Hành trình bắt đầu từ một ý tưởng nhỏ.</h2></aside></div></main>}

function Trip({trip,setPage}){return <main className="page"><div className="title"><div><h1>{trip.origin} → {trip.destination}</h1><p>15/09 – 18/09/2026 · {trip.days} ngày · 2 người</p></div><button className="green">Chỉnh sửa</button></div><div className="subnav"><button>Tổng quan</button><button>Lịch trình</button><button onClick={()=>setPage('checklist')}>Checklist</button><button>Ghi chú</button></div><div className="tripgrid"><section className="card progress"><b className="ring big">60%</b><div><h3>Tiến độ chuyến đi</h3><p>✓ Lịch trình (3/4)<br/>✓ Checklist (12/20)<br/>✓ Địa điểm đã lưu (5)<br/>✓ Ghi chú (2)</p></div><div className="info"><b>Thông tin nhanh</b><p>◈ ~320 km &nbsp; ◷ ~7 giờ<br/>⌂ Chi phí dự kiến ~1.200.000đ/người</p></div></section><section className="card mapcard"><iframe title="trip map" className="map large" src={`https://www.google.com/maps?q=${encodeURIComponent(trip.destination)}&output=embed`}></iframe><button className="mapopen" onClick={()=>directions(trip.origin,trip.destination)}>Mở Google Maps ↗</button></section></div><section className="box itinerary"><div className="title"><h2>Lịch trình gợi ý</h2><button onClick={()=>setPage('ai')}>Nhờ AI điều chỉnh →</button></div>{[['Ngày 1',`${trip.origin} → Tuyên Quang`],['Ngày 2','Tuyên Quang → Đồng Văn'],['Ngày 3','Khám phá Đồng Văn'],['Ngày 4',`Đồng Văn → ${trip.origin}`]].map(x=><div className="it" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><button onClick={()=>directions(x[1].split('→')[0],x[1].split('→')[1]||trip.destination)}>Maps ↗</button></div>)}</section></main>}

function Checklist(){const init=[['CCCD/CMND',1],['Giấy phép lái xe',1],['Đăng ký xe',0],['Bảo hiểm xe máy',1],['Kiểm tra lốp xe',1],['Kiểm tra dầu nhớt',1],['Kiểm tra phanh',0],['Kiểm tra đèn, còi',1],['Mang theo bộ vá xe',1],['Áo mưa',0],['Sạc dự phòng',1]];const [items,setItems]=useState(init);let done=items.filter(x=>x[1]).length;return <main className="page narrow"><div className="title"><div><h1>Checklist</h1><p>Chuẩn bị tốt hơn trước khi lên đường.</p></div><b>{done}/{items.length}</b></div><div className="bar"><i style={{width:`${done/items.length*100}%`}}/></div><section className="card checks">{items.map((x,i)=><label key={x[0]}><input type="checkbox" checked={!!x[1]} onChange={()=>setItems(items.map((a,j)=>j===i?[a[0],!a[1]]:a))}/><span>{x[0]}</span></label>)}<button className="soft" onClick={()=>{let v=prompt('Tên mục cần thêm');if(v)setItems([...items,[v,0]])}}>＋ Thêm mục</button></section></main>}

function Tools({setPage}){return <main className="page"><h1>Công cụ hỗ trợ</h1><p>Những công cụ nhỏ, cho hành trình lớn hơn.</p><div className="toolgrid"><button onClick={()=>setPage('checklist')}><span>✅</span><h3>Checklist</h3><p>Chuẩn bị giấy tờ, hành lý và tình trạng xe.</p></button>{tools.map(t=><button key={t[1]} onClick={()=>searchMaps(t[2])}><span>{t[0]}</span><h3>{t[1]}</h3><p>Tìm nhanh trên Google Maps khi cần.</p></button>)}<button onClick={()=>setPage('ai')}><span>➤</span><h3>AI Assistant</h3><p>Hỏi gì cũng có đáp án cho chuyến đi.</p></button></div></main>}

function AI({trip}){const [msgs,setMsgs]=useState([{r:'ai',t:'Xin chào! Tôi là RideMate AI. Tôi có thể hỗ trợ lịch trình, checklist, chuẩn bị xe và xử lý tình huống.'}]);const [txt,setTxt]=useState('');const send=t=>{t=t||txt;if(!t.trim())return;let q=t.toLowerCase(),a=`Với chuyến ${trip.origin} → ${trip.destination} trong ${trip.days} ngày, hãy giữ lịch trình vừa sức và kiểm tra xe trước khi đi.`;if(q.includes('thủng')||q.includes('sự cố'))a='Đưa xe vào vị trí an toàn, kiểm tra lốp và dùng công cụ “Sửa xe” để mở Google Maps tìm điểm hỗ trợ gần nhất.';if(q.includes('checklist'))a='Gợi ý: CCCD, bằng lái, đăng ký xe, áo mưa, sạc dự phòng, nước, bộ vá lốp; kiểm tra lốp, phanh, dầu nhớt và đèn.';if(q.includes('lịch trình')||q.includes('hà giang'))a=`Gợi ý ${trip.days} ngày: ngày 1 đi Hà Giang, ngày 2 Đồng Văn, ngày 3 Mèo Vạc, ngày 4 quay về ${trip.origin}.`;setMsgs([...msgs,{r:'user',t},{r:'ai',t:a}]);setTxt('')};return <main className="page narrow"><section className="card chat"><div className="chathead"><h1>AI Assistant</h1><span>● Đang online</span></div><div className="prompts">{['Gợi ý lịch trình Hà Giang 4 ngày','Tạo checklist','Xe tôi bị thủng lốp'].map(p=><button key={p} onClick={()=>send(p)}>{p}</button>)}</div><div className="messages">{msgs.map((m,i)=><div className={`bubble ${m.r}`} key={i}>{m.t}</div>)}</div><div className="inputrow"><input value={txt} onChange={e=>setTxt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Nhập câu hỏi..."/><button onClick={()=>send()}>➤</button></div></section></main>}

function Journal(){return <main className="page"><div className="title"><div><h1>Nhật ký hành trình</h1><p>Lưu lại những khoảnh khắc đáng nhớ.</p></div><button className="green">＋ Tạo bài mới</button></div><div className="journal">{routes.slice(0,3).map((r,i)=><article key={r[0]}><img src={r[3]}/><div><small>1{i+5}/09/2026</small><h3>Ngày {i+1}: {r[0]}</h3><p>Cung đường đẹp, nhiều trải nghiệm đáng nhớ.</p></div></article>)}<button className="add">＋<small>Thêm bài viết</small></button></div></main>}

function App(){const [page,setPage]=useState('home');const [trip,setTrip]=useState({origin:'Hà Nội',destination:'Hà Giang',date:'2026-09-15',days:4});let c=page==='home'?<Home trip={trip} setTrip={setTrip} setPage={setPage}/>:page==='create'?<Create trip={trip} setTrip={setTrip} setPage={setPage}/>:page==='trip'?<Trip trip={trip} setPage={setPage}/>:page==='checklist'?<Checklist/>:page==='tools'?<Tools setPage={setPage}/>:page==='ai'?<AI trip={trip}/>:<Journal/>;return <><Nav page={page} setPage={setPage}/>{c}<footer><b>▲ RideMate</b><span>Đi xa hơn, an toàn hơn, trải nghiệm nhiều hơn.</span><span>Giới thiệu · Hỗ trợ · Góp ý · Chính sách bảo mật</span></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
