import React, { useMemo, useRef, useState } from 'react';
import ToolIcon from './ToolIcon.jsx';
import RouteMap from './RouteMap.jsx';
import { useTripRoute } from './TripRouteContext.jsx';
import { supportTypes, directionsUrl, placeDirectionsUrl, validPoint } from './route-data.js';
import { plannedPlaces } from './planned-places.js';
import { travelTime } from './motorcycle-routing.js';
import TripWeather from './TripWeather.jsx';

export default function RouteOverview({ trip, children }) {
  const current = useTripRoute();
  const [selected, setSelected] = useState(null);
  const [visible, setVisible] = useState({});
  const mapSection = useRef(null);
  const pendingPlaces = useMemo(() => plannedPlaces(trip).filter(place => validPoint(place.coordinates)), [trip]);
  const pendingCenter = trip.originPoint?.label === trip.origin && validPoint(trip.originPoint?.coordinates) ? trip.originPoint : pendingPlaces[0];
  const select = place => { setVisible(value => ({ ...value, [place.type]: true })); setSelected({ ...place }); mapSection.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const maps = current.route ? directionsUrl(current.route.start, current.route.end) : null;
  const toggleType = key => { setSelected(null); setVisible(value => ({ ...value, [key]: !value[key] })); };
  return <div className="tripgrid route-overview"><section className="card quick-information">{children}<section className="route-quick"><h3>Thông tin nhanh</h3><p className="route-caption">Chặng đi: {trip.origin} <ToolIcon name="arrowRight" className="inline-icon"/> {trip.destination}</p>{current.route && <><div className="route-metrics"><span><b>{Math.round(current.route.distanceKm).toLocaleString('vi-VN')} km</b><small>Tổng tuyến đã nối</small></span><span><b>{travelTime(current.route.durationSeconds)}</b><small>Valhalla xe máy · chưa dừng nghỉ</small></span></div><p className="route-caption">Định vị: {current.route.start.label} <ToolIcon name="arrowRight" className="inline-icon"/> {current.route.end.label}</p></>}
      {current.route?.estimate && <div className="route-time-plan"><b>Dự trù hành trình gồm nghỉ ngắn: {travelTime(current.route.estimate.total)} – {travelTime(current.route.estimate.upper)}</b><p className="route-caption">Thời gian Valhalla ở trên là ước tính theo dữ liệu đường, chưa có giao thông trực tiếp. Phần dự trù riêng lấy tốc độ trung bình không quá 40 km/h; nếu dịch vụ tính chậm hơn thì giữ thời gian dài hơn. Nghỉ 15 phút sau mỗi 2 giờ chạy; đầu trên thêm 25% thời gian chạy dự phòng. Chưa gồm ăn uống, tham quan, ngủ qua đêm hoặc giao thông thực tế. Đây là ước tính lập kế hoạch, không phải giờ đến chắc chắn.</p></div>}<TripWeather trip={trip} /><h4>Điểm hỗ trợ gần cung đường</h4><p className="route-caption">Tối đa 30 điểm mỗi loại, phân bố dọc tuyến trong phạm vi khoảng 1,5 km theo đường thẳng. Bấm ghim để xem tên và chỉ đường; dữ liệu có thể chưa đầy đủ.</p>{(current.loading || current.placesLoading) && <p role="status" className="route-message">{current.loading ? 'Đang tìm cung đường…' : 'Đang tìm các điểm hỗ trợ dọc tuyến…'}</p>}{current.placesError && <p role="status" className="route-message">{current.placesError}</p>}
      {Object.entries(supportTypes).map(([key, type]) => <section className={`support-group support-${key}`} key={key}><h4><button className="support-toggle" aria-pressed={visible[key]} onClick={() => { toggleType(key); mapSection.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }}><ToolIcon name={type.icon} className="inline-icon"/> {type.label} ({current.places.filter(place => place.type === key).length}) · {visible[key] ? "Ẩn ghim" : "Hiện ghim"}</button></h4><div role="list" aria-label={type.label}>{current.places.filter(place => place.type === key).map(place => <div key={place.id} className="support-row" role="listitem"><button type="button" className="support-place" onClick={() => select(place)} aria-label={`Xem trên bản đồ: ${place.name}`} title={[place.name, place.address].filter(Boolean).join(' — ')}><span className="support-name">{place.name}</span><span className="support-distance">{place.distanceMeters < 1000 ? `${Math.max(10, Math.round(place.distanceMeters / 10) * 10)} m` : `${(place.distanceMeters / 1000).toFixed(1)} km`}</span></button><a className="support-map-link" href={placeDirectionsUrl(place)} target="_blank" rel="noreferrer" aria-label={`Chỉ đường đến ${place.name}`} title="Chỉ đường đến đây"><ToolIcon name="external" className="inline-icon"/></a></div>)}</div>{!current.loading && !current.placesLoading && !current.places.some(place => place.type === key) && <p className="route-caption">{current.placesError || current.error ? 'Chưa có dữ liệu để hiển thị.' : 'Chưa tìm thấy điểm phù hợp trong dữ liệu bản đồ.'}</p>}<a className="support-search" href={`https://www.google.com/maps/search/?${new URLSearchParams({ api: '1', query: `${type.label} gần ${trip.destination}` })}`} target="_blank" rel="noreferrer">Tìm thêm quanh {trip.destination} <ToolIcon name="external" className="inline-icon"/></a></section>)}
      <p className="route-caption">Nguồn: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>. Danh sách có thể chưa đầy đủ; giờ mở cửa chưa được xác minh.</p></section></section>
      <section ref={mapSection} className="card journey-route-map">
        <div className="title"><h3>Cung đường trên bản đồ</h3>{maps && <a href={maps} target="_blank" rel="noreferrer">Mở Google Maps <ToolIcon name="external" className="inline-icon"/></a>}</div>
        <p className="route-caption">Tuyến xe máy nối điểm xuất phát → các điểm có tọa độ theo thứ tự ngày/lịch trình → điểm đến. Bấm một chặng bên dưới để phóng tới đoạn đường đó.</p>
        {current.route ? <>
          <div className="route-legend" aria-label="Hiển thị điểm hỗ trợ dọc tuyến">
            {Object.entries(supportTypes).map(([key, type]) => <button key={key} aria-pressed={visible[key]} onClick={() => toggleType(key)}><ToolIcon name={type.icon} className="inline-icon"/> {type.label} ({current.places.filter(place => place.type === key).length})</button>)}
          </div>
          <p className="route-caption" role="status">{current.placesLoading ? `Đang tìm điểm hỗ trợ… ${current.progress}` : current.placesError || (Object.values(visible).some(Boolean) ? 'Bấm ghim để xem tên và chọn “Chỉ đường đến đây”.' : 'Chọn loại điểm hỗ trợ để hiện ghim dọc đường.')}</p>
          {!!current.route.unresolved?.length && <p className="route-message">{current.route.unresolved.length} điểm chưa có tọa độ nên chưa được nối vào tuyến. Mở Hành trình → Lịch trình → Chọn vị trí để bổ sung.</p>}
          <p className="route-caption">Điểm đi: {current.route.start.label}. Điểm đến: {current.route.end.label}. Tỉnh/thành được định vị bằng điểm đại diện, không phải địa chỉ cụ thể của bạn.</p>
          <p className="route-caption">Chỉ hiển thị tuyến trong Việt Nam theo ranh giới OpenStreetMap. Đã yêu cầu tránh cao tốc và kiểm tra các đoạn được nhận diện là cao tốc; vẫn cần tuân theo biển báo thực tế. Google Maps tự tính tuyến riêng từ hai đầu tuyến, không áp dụng bộ lọc biên giới của web; hãy kiểm tra trước khi đi. Nếu Google không hỗ trợ chế độ xe máy tại vị trí truy cập, mở ứng dụng Google Maps và chọn xe máy; thời gian ô tô không tương đương.</p>
        </> : <p className="route-message" role="status">{current.loading ? 'Đang xác định điểm đi–đến và tải cung đường… Bản đồ vẫn có thể sử dụng trong lúc chờ.' : current.error || 'Chưa tải được cung đường.'}</p>}
        <RouteMap route={current.route} center={current.route ? undefined : pendingCenter} places={current.route ? current.places : pendingPlaces} visible={current.route ? visible : { planned: true }} selected={selected} />
        {!current.loading && (current.error || current.placesError) && <button className="soft" onClick={current.retry}>Thử tải lại</button>}
        <p className="route-caption">MapLibre · OpenFreeMap / OpenStreetMap · Tuyến xe máy Valhalla · yêu cầu tránh cao tốc; kiểm tra biển báo thực tế</p>
      </section></div>;
}
